site_name: reallife_client_mac

theme:
  name: "material"
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - mkdocstrings # 自动搜索代码

nav:
  - Index: index.md
  - Tutorial: 
    - core : core.md
  - Use Case: use_case.md